### ISSUE TITLE
Got error when running `pnpm dev` in `advisor-guide` directory

### ISSUE THREAD

**Issue by ryanlinjui** [JacobLinCool/advisor-guide#4]
I got `TypeError: Cannot read properties of undefined (reading 'length')`. And I already add remote db url environment variable and download data directory which contains `index.json` and institutions json data by running `build-data.ts`.

**Comment by JacobLinCool** [comment]
If you want to use the embedded data, just put the institution JSON files in the `packages/advisor-guide/data` directory; `index.json` is not needed.  
If you want to use the remote data, you should upload the institution JSON files along with the `index.json`.  

What settings values did you use?

**Comment by ryanlinjui** [comment]
Thanks a lot. It works after removing `index.json`.
